/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyecto_PvZ;

import javax.swing.JProgressBar;

/**
 *
 * @author luism
 */
public class PvZ extends javax.swing.JFrame {

    /**
     * Creates new form PvZ
     */
    public PvZ() {
        initComponents();
        jLLoadingBar2.setVisible(false);
        jLLoadingBar3.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPLoadingScreen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPBLoading = new javax.swing.JProgressBar();
        jLLoadingBar1 = new javax.swing.JLabel();
        jLLoadingBar2 = new javax.swing.JLabel();
        jLLoadingBar3 = new javax.swing.JLabel();
        jLLoadingScreenBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPLoadingScreen.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPLoadingScreen.setPreferredSize(new java.awt.Dimension(1920, 800));
        jPLoadingScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 14)); // NOI18N
        jLabel1.setText("Loading...");
        jPLoadingScreen.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 90, -1));

        jPBLoading.setBackground(new java.awt.Color(0, 0, 0));
        jPBLoading.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPBLoading.setForeground(new java.awt.Color(0, 0, 0));
        jPBLoading.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jPBLoadingStateChanged(evt);
            }
        });
        jPLoadingScreen.add(jPBLoading, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 390, 40));

        jLLoadingBar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/loadingscreen12.png"))); // NOI18N
        jPLoadingScreen.add(jLLoadingBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 400, 120));

        jLLoadingBar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/loadingscreen22.png"))); // NOI18N
        jPLoadingScreen.add(jLLoadingBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 390, -1));

        jLLoadingBar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/loadingscreen33.png"))); // NOI18N
        jPLoadingScreen.add(jLLoadingBar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 290, 400, -1));

        jLLoadingScreenBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/88298011cbb1b92aa9d2c1c7d9c1edf3 (1).jpg"))); // NOI18N
        jLLoadingScreenBG.setMaximumSize(new java.awt.Dimension(1920, 800));
        jPLoadingScreen.add(jLLoadingScreenBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPLoadingScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPLoadingScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPBLoadingStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jPBLoadingStateChanged
            // TODO add your handling code here:
    }//GEN-LAST:event_jPBLoadingStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PvZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PvZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PvZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PvZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PvZ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLLoadingBar1;
    private javax.swing.JLabel jLLoadingBar2;
    private javax.swing.JLabel jLLoadingBar3;
    private javax.swing.JLabel jLLoadingScreenBG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jPBLoading;
    private javax.swing.JPanel jPLoadingScreen;
    // End of variables declaration//GEN-END:variables
    
}
